proxygen: fix clang exposed compilation errors
Summary:
When build `proxygen/lib/http/session/test` with clang dev, it fails with two compilation errors:
```
proxygen/lib/http/session/test/HTTPDownstreamSessionTest.cpp:1754:58: error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]
clientCodec.generateHeader(requests, streamID, req, 0, nullptr);
~~~~~~~~~~~                                            ^~~~~~~
false
proxygen/lib/http/session/test/HTTPDownstreamSessionTest.cpp:1758:58: error: implicit conversion of nullptr constant to 'bool' [-Werror,-Wnull-conversion]
clientCodec.generateHeader(requests, streamID, req, 0, nullptr);
~~~~~~~~~~~                                            ^~~~~~~
false
```

Method signature from https://fburl.com/124570037:

```lang=cpp
void SPDYCodec::generateHeader(folly::IOBufQueue& writeBuf,
StreamID stream,
const HTTPMessage& msg,
StreamID assocStream = 0,
bool eom = false,
HTTPHeaderSize* size = nullptr) override;
```
Removing last argument since it matches with the default one, assuming that default eom argument is supposed to be used here.

Test Plan: Verify `proxygen/lib/http/session/test` can be build with clang dev without compilation errors.

Reviewed By: praveenr@fb.com

Subscribers: viswanath, bmatheny, mathieubaudet, nikanick, ldbrandy

FB internal diff: D2181549

Signature: t1:2181549:1435183444:a86d5cadb480bc72a88d1f0d9f9e2a199a429454