Readd GFlags portability header to TestMain
Commit 3842e216ca718c814a40fe948e6a839513de1ef2 removed this header
as it was considered unused.

proxygen/lib/test/TestMain.cpp:16:3: error: ‘gflags’ has not been declared
   16 |   gflags::ParseCommandLineFlags(&argc, &argv, true);
      |   ^~~~~~