Initial CMake test support for Proxygen (#260)
Summary:
ProxygenTest.cmake initializes CTest and enables unit tests based on the
value of `BUILD_TESTING` (provided by CTest). This option is `OFF` by
default.

The module provides a function called `proxygen_add_test()`, which makes
it possible to declare tests without boilerplates:

```
proxygen_add_test(TARGET target
                  [SOURCES src1...]
                  [DEPENDS dep1...]
                  [INCLUDES inc1...]
                  [EXTRA_ARGS arg1...]
                  [WORKING_DIRECTORY dir]
                  [PREFIX prefix]
)
```

----

3 tests are left out:
- proxygen/httpserver/samples/echo/test
- HTTPServerTest.cpp (`undefined reference to folly::ssl::SSLServerOptions::kCipherList`)
- HTTPSessionAcceptorTest.cpp (`undefined reference to folly::ssl::SSLServerOptions::kCipherList`)

Note:
`GMOCK_METHOD1_(, noexcept, ...` does not work with GMock v1.8.1.
Pull Request resolved: https://github.com/facebook/proxygen/pull/260

Reviewed By: afrind

Differential Revision: D14680788

Pulled By: lnicco

fbshipit-source-id: e183cd3fbb33d40735ef2111448ab8f4d51e5842