Add missing ResponseBuilder.h include to DirectResponseHandler.h
Summary:
Without this include line DirectResponseHandler is not compiling if noone included ResponseBuilder before.

Here's compile error from my project. I can always include ResponseBuilder before DirectResponseHandler but I thought it would be nice to have it here.

    In file included from proxygen/facebook/websocketserver/WebSocketHandlerAdapters.cpp:5:0:
    ./proxygen/httpserver/filters/DirectResponseHandler.h: In member function 'virtual void proxygen::DirectResponseHandler::onEOM()':
    ./proxygen/httpserver/filters/DirectResponseHandler.h:39:32: error: 'ResponseBuilder' was not declared in this scope

Reviewed By: rpraveen

Differential Revision: D2797111

fb-gh-sync-id: e0b39c99834694c445d5acdef26fc87c472e8fdd