Add missing portability header to SessionPoolTest
SessionPoolTest.cpp: In function ‘int main(int, char**)’:
SessionPoolTest.cpp:718:3: error: ‘gflags’ has not been declared
  718 |   gflags::ParseCommandLineFlags(&argc, &argv, true);
      |   ^~~~~~