proxygen: test: fix sign-compare warning/error with gcc-4.9 (tiny)
Summary: avoid this build failure:

  proxygen/lib/http/session/test/HTTPDownstreamSessionTest.cpp: In instantiation of 'void gtest_case_HTTPDownstreamTest_::testMaxTxns<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = SPDY3CodecPair]':
  ./proxygen/lib/http/session/ByteEvents.h:95:7:   required from here
  proxygen/lib/http/session/test/HTTPDownstreamSessionTest.cpp:1329:24: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

Reviewed By: igorsugak

Differential Revision: D2668977

fb-gh-sync-id: d8858bc3ca36de898795abee7f70029e045ed357