Add missing portability header to SessionPoolTest (#276)
Summary:
```
SessionPoolTest.cpp: In function ‘int main(int, char**)’:
SessionPoolTest.cpp:718:3: error: ‘gflags’ has not been declared
  718 |   gflags::ParseCommandLineFlags(&argc, &argv, true);
      |   ^~~~~~
```
Pull Request resolved: https://github.com/facebook/proxygen/pull/276

Reviewed By: jalopezsilva

Differential Revision: D16639737

Pulled By: lnicco

fbshipit-source-id: acd607f9adfd0d64dc7ab25a82f1033f85fa8a16