Readd GFlags portability header to TestMain (#281)
Summary:
Commit 3842e216ca718c814a40fe948e6a839513de1ef2 removed this header as it was considered unused.

```
proxygen/lib/test/TestMain.cpp:16:3: error: ‘gflags’ has not been declared
   16 |   gflags::ParseCommandLineFlags(&argc, &argv, true);
      |   ^~~~~~
```
Pull Request resolved: https://github.com/facebook/proxygen/pull/281

Reviewed By: sharma95

Differential Revision: D17075284

Pulled By: lnicco

fbshipit-source-id: 376c259da29fbf8cd68fa79c95c6ce95b5d5c435